### ISSUE TITLE
Create search bar

### ISSUE THREAD

**Issue by irvine5k** [Flutterando/music_player_app#2]
![image](https://user-images.githubusercontent.com/32758755/85933439-5b5e9680-b8ad-11ea-986b-83cb208fa0ba.png)
https://cdn.dribbble.com/users/121337/screenshots/12389575/media/746169132ec45b15992c0383745b6d2b.png

**Comment by luizeduardotj** [comment]
Eu tento essa

**Comment by cmatheus3103** [comment]
it's mine!
